name: DarkCubeSystem
version: $version
api-version: "1.21"
main: eu.darkcube.system.impl.bukkit.cloudnet.BukkitCloudNet
loader: eu.darkcube.system.impl.bukkit.cloudnet.ModernPaperLoader
has-open-classloader: true
bootstrapper: eu.darkcube.system.impl.bukkit.cloudnet.ModernPaperBootstrap
provides:
  - System
dependencies:
  server:
    ViaVersion:
      required: false
    LuckPerms:
      required: false