metadata.format.version = "1.1"

[versions]
cloudnet = "4.0.0-RC9"
annotations = "24.1.0"
shadow = "8.1.2"
brigadier = "1.0.18"
gson = "2.10.1"
adventure = "4.17.0"
adventure-platform = "4.3.2"
viaversion = "4.9.4-darkcube-20240419.214635-1"

[libraries]
viaversion = { group = "com.viaversion", name = "viaversion-api", version.ref = "viaversion" }
viaversion-common = { group = "com.viaversion", name = "viaversion-common", version.ref = "viaversion" }
viaversion-velocity = { group = "com.viaversion", name = "viaversion-velocity", version.ref = "viaversion" }
viaversion-bukkit = { group = "com.viaversion", name = "viaversion-bukkit", version.ref = "viaversion" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-text-serializer-gson-legacy-impl = { group = "net.kyori", name = "adventure-text-serializer-gson-legacy-impl", version.ref = "adventure" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

cloudnet-driver = { group = "eu.cloudnetservice.cloudnet", name = "driver", version.ref = "cloudnet" }
cloudnet-bridge = { group = "eu.cloudnetservice.cloudnet", name = "bridge", version.ref = "cloudnet" }
cloudnet-node = { group = "eu.cloudnetservice.cloudnet", name = "node", version.ref = "cloudnet" }
cloudnet-wrapper = { group = "eu.cloudnetservice.cloudnet", name = "wrapper-jvm", version.ref = "cloudnet" }

[bundles]
adventure = [
    "adventure-api",
    "adventure-platform-bukkit",
    "adventure-text-serializer-gson",
    "adventure-text-serializer-gson-legacy-impl",
    "adventure-text-serializer-legacy",
    "adventure-text-serializer-plain"
]

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
