name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CACHE_PATHS: |
    ~/.gradle/caches
    **/.gradle
    **/build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Restore Cache for Branch
        if: ${{ github.head_ref == null }}
        id: restore-cache-branch
        uses: actions/cache/restore@v4
        with:
          key: gradle-cache-${{ github.ref_name }}
          path: ${{ env.CACHE_PATHS }}
      - name: Restore Cache for PR
        if: ${{ github.head_ref != null }}
        id: restore-cache-pr
        uses: actions/cache/restore@v4
        with:
          key: gradle-cache-${{ github.head_ref }}
          path: ${{ env.CACHE_PATHS }}
          restore-keys: |
            gradle-cache-${{ github.base_ref }}

      - name: Print Branch
        run: |
          echo Base ref ${{ github.base_ref }}
          echo Head ref ${{ github.head_ref }}
          echo Ref ${{ github.ref }}
          echo Ref Name ${{ github.ref_name }}
          echo "Cache path: $CACHE_PATHS"
      - name: Print Runner
        run: echo Runner ${{ runner.os }}

      - name: Build with Gradle Wrapper
        run: ./gradlew -PDarkCubeUsername="${{ secrets.REPOSITORY_USERNAME }}" -PDarkCubePassword="${{ secrets.REPOSITORY_PASSWORD }}" build --no-configuration-cache --no-daemon

      - name: Delete Cache for Branch
        if: ${{ github.head_ref == null }} && ${{ steps.restore-cache-branch.outputs.cache-hit }}
        id: delete-cache-branch
        run: |
          gh cache delete ${{ steps.restore-cache-branch.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Cache for PR
        if: ${{ github.head_ref != null }} && ${{ steps.restore-cache-pr.outputs.cache-hit }}
        id: delete-cache-pr
        run: |
          gh cache delete ${{ steps.restore-cache-pr.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Cache for Branch
        if: ${{ github.head_ref == null }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ steps.restore-cache-branch.outputs.cache-primary-key }}
      - name: Save Cache for PR
        if: ${{ github.head_ref != null }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ steps.restore-cache-pr.outputs.cache-primary-key }}