name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GRADLE_USER_HOME: |
    ~/.gradle
  DEPENDENCY_CACHE_PATHS: |
    **/.gradle/caches/paperweight
    ~/.gradle/caches
  BUILD_CACHE_PATHS: |
    **/build
  GRADLE_CACHE_PATHS: |
    ~/.gradle/wrapper

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Prepare Cache
        id: cache-vars
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.base_ref }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          PR=$(if [ "$HEAD_REF" = "" ]; then echo false; else echo true; fi)
          if [ "$PR" = "true" ]; then
            echo "gradle-cache-key=gradle-cache-$HEAD_REF" >> "$GITHUB_OUTPUT"
            echo "gradle-cache-restore-keys=gradle-cache-$BASE_REF" >> "$GITHUB_OUTPUT"
            echo "build-cache-key=build-cache-$HEAD_REF" >> "$GITHUB_OUTPUT"
            echo "build-cache-restore-keys=build-cache-$BASE_REF" >> "$GITHUB_OUTPUT"
            echo "dependency-cache-key=dependency-cache-$HEAD_REF" >> "$GITHUB_OUTPUT"
            echo "dependency-cache-restore-keys=dependency-cache-$BASE_REF" >> "$GITHUB_OUTPUT"
          else
            echo "gradle-cache-key=gradle-cache-$REF_NAME" >> "$GITHUB_OUTPUT"
            echo "build-cache-key=build-cache-$REF_NAME" >> "$GITHUB_OUTPUT"
            echo "dependency-cache-key=dependency-cache-$REF_NAME" >> "$GITHUB_OUTPUT"
          fi

      - name: Restore Gradle Cache
        id: restore-gradle-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.GRADLE_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.gradle-cache-key }}
          restore-keys: ${{ steps.cache-vars.outputs.gradle-cache-restore-keys }}
      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.build-cache-key }}
          restore-keys: ${{ steps.cache-vars.outputs.build-cache-restore-keys }}
      - name: Restore Dependency Cache
        id: restore-dependency-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCY_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.dependency-cache-key }}
          restore-keys: ${{ steps.cache-vars.outputs.dependency-cache-restore-keys }}

      - name: Store Cache Checksums
        run: |
          echo "Current Hash: ${{ hashFiles(env.GRADLE_CACHE_PATHS) }}"
          echo "Current Hash: ${{ hashFiles(env.BUILD_CACHE_PATHS) }}"
          echo "Current Hash: ${{ hashFiles(env.DEPENDENCY_CACHE_PATHS) }}"

      - name: Build with Gradle Wrapper
        run: ./gradlew -PDarkCubeUsername="${{ secrets.REPOSITORY_USERNAME }}" -PDarkCubePassword="${{ secrets.REPOSITORY_PASSWORD }}" build --no-configuration-cache --no-daemon

      - name: Evaluate Changed Cache Files
        run: |
          echo "Current Hash: ${{ hashFiles(env.GRADLE_CACHE_PATHS) }}"
          echo "Current Hash: ${{ hashFiles(env.BUILD_CACHE_PATHS) }}"
          echo "Current Hash: ${{ hashFiles(env.DEPENDENCY_CACHE_PATHS) }}"

      - name: Delete previous Gradle Cache
        if: ${{ steps.restore-gradle-cache.outputs.cache-hit }}
        id: delete-gradle-cache
        run: |
          gh cache delete ${{ steps.restore-gradle-cache.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete previous Build Cache
        if: ${{ steps.restore-build-cache.outputs.cache-hit }}
        id: delete-build-cache
        run: |
          gh cache delete ${{ steps.restore-build-cache.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete previous Dependency Cache
        if: ${{ steps.restore-dependency-cache.outputs.cache-hit }}
        id: delete-dependency-cache
        run: |
          gh cache delete ${{ steps.restore-dependency-cache.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Save new Gradle Cache
        id: save-gradle-cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.GRADLE_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.gradle-cache-key }}
      - name: Save new Build Cache
        id: save-build-cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.build-cache-key }}
      - name: Save new Dependency Cache
        id: save-dependency-cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCY_CACHE_PATHS }}
          key: ${{ steps.cache-vars.outputs.dependency-cache-key }}
