name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DEPENDENCY_CACHE_PATHS: |
    **/.gradle/caches/paperweight
    ~/.gradle/caches
  BUILD_CACHE_PATHS: |
    **/build
    .gradle/configuration-cache
  GRADLE_CACHE_PATHS: |
    ~/.gradle/wrapper

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew -PDarkCubeUsername="${{ secrets.REPOSITORY_USERNAME }}" -PDarkCubePassword="${{ secrets.REPOSITORY_PASSWORD }}" build --configuration-cache-problems=warn --no-daemon --stacktrace
