name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

#    - name: Setup Gradle
#      uses: gradle/actions/setup-gradle@v3

    - name: Setup Caching
      uses: actions/cache@v4
      with:
        key: gradle-cache-${{ github.ref }}
        path: |
          ~/.gradle
          **/.gradle
          **/build
        restore-keys: |
          gradle-cache-${{ github.ref}}
          gradle-cache-

    - name: Print Branch
      run: echo Running on branch ${{ github.ref }}
    - name: Print Runner
      run: echo Runner ${{ runner.os }}

    - name: Build with Gradle Wrapper
      run: ./gradlew -PDarkCubeUsername="${{ secrets.REPOSITORY_USERNAME }}" -PDarkCubePassword="${{ secrets.REPOSITORY_PASSWORD }}" build --no-configuration-cache
