name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CACHE_PATHS: |
    ~/.gradle
    **/.gradle
    **/build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Caching for Branch
        if: ${{ github.head_ref == null }}
        id: cache-branch
        uses: actions/cache@v4
        with:
          key: gradle-cache-${{ github.ref_name }}
          path: $CACHE_PATHS
      - name: Setup Caching for PR
        if: ${{ github.head_ref != null }}
        id: cache-pr
        uses: actions/cache@v4
        with:
          key: gradle-cache-${{ github.head_ref }}
          path: ${{ env.CACHE_PATHS }}
          restore-keys: |
            gradle-cache-${{ github.base_ref }}

      - name: Print Branch
        run: |
          echo Base ref ${{ github.base_ref }}
          echo Head ref ${{ github.head_ref }}
          echo Ref ${{ github.ref }}
          echo Ref Name ${{ github.ref_name }}
          echo "Cache path: $CACHE_PATHS"
      - name: Print Runner
        run: echo Runner ${{ runner.os }}

#      - name: Build with Gradle Wrapper
#        run: ./gradlew -PDarkCubeUsername="${{ secrets.REPOSITORY_USERNAME }}" -PDarkCubePassword="${{ secrets.REPOSITORY_PASSWORD }}" build --no-configuration-cache
